Fektetett órarend hibás kiírás javítása
refilc/naplo pull request #131
Opened 2024-09-07 15:12 UTC by balint1414

Androidos telefonon teszteltem réggebben, akkor működött.

2024-09-12 10:16 UTC, CsPS0 reviewed
Yeah végre!

2024-09-26 17:24 UTC, kimaah requested changes
ez megoli a 0. orat, azt nem irja ki igy for some reason

2024-11-05 16:56 UTC, PPearoo approved these changes

2024-11-05 16:58 UTC, CsPS0 commented
🥳

2024-11-05 23:04 UTC, aggiczy commented
abból nem lesz további gond, hogy nem írja ki a 0. órát?

(https://github.com/refilc/naplo/pull/131#pullrequestreview-2331935248)

2024-11-05 23:06 UTC, PPearoo commented
de

2024-11-05 23:06 UTC, aggiczy commented
akkor nem kéne előbb kijavítani (@balint1414), mielőtt bekerül a fix? 😂

2024-11-06 11:15 UTC, balint1414 commented
vicces lenne kijavítani, igen, csak nincs 0. órám, így nem igazán tudok mit kezdeni, de majd ha lesz időm/kedvem megprobbálkozok vlmt alkotni

2024-11-07 20:55 UTC, BalazsManus commented
holnap sajat branchembe bemergelem es ranezek

2024-11-15 15:40 UTC, BalazsManus commented
ha ezt a sort: `(e) => e.lessonIndex == index.toString());`
atirod erre: `(e) => e.lessonIndex == (index - 1).toString());`

akkor az osszes ora latszodik viszont a nulladik oras napok elcsusznak es 6 helyett 7 orad lesz a nulladik meg atcsuszik elso oraba, viszont mutatja az osszeset

2024-11-15 15:48 UTC, BalazsManus requested changes
well, it kinda works if `(e) => e.lessonIndex == (index - 1).toString());`

2024-11-15 18:28 UTC, balint1414 commented
@BalazsManus eredeti hibát hozza elő, nem jeleníti meg az utolsó órát

2024-11-15 18:39 UTC, BalazsManus commented
> @BalazsManus eredeti hibát hozza elő, nem jeleníti meg az utolsó órát

Nálam megjelenítette, u can try my apk https://depot.mnus.hu/depo/fdroid/repo/hu.mnus.refilc.rolling_20241115.apk

2024-11-15 19:40 UTC, balint1414 commented
![image](https://github.com/user-attachments/assets/0a254916-2a1b-4c3a-b43b-ed8750719661)
elvilegesen fixelve, mostmár a 0. és a legutolsó órát is megjeleníti, bár az is tény, hogy saját self-hosted webszerverről kérte le az órarendet, mivel alapból nincs 0. órám, tehát nem biztos h élesbe is megy.

2024-11-15 20:00 UTC, kimaah approved these changes
seems fine

2024-11-15 20:00 UTC, merged

2024-11-28 07:26 UTC, CsPS0 commented
![Screenshot_20241128_082607.jpg](https://github.com/user-attachments/assets/f37ea042-c16e-4b4f-b9de-d94e651e6de4)

13. 14. 15. 16. Órát nem mutatja 🤓