12-től van délután
refilc/naplo pull request #88
Opened 2024-02-24 20:24 UTC by pml68

[![image](https://github.com/refilc/naplo/assets/116908301/44218aca-2f89-4817-8565-8719850f15da)](https://discord.com/channels/1111649116020285532/1209425375483011142)

2024-02-24 20:32 UTC, pml68 commented
Még egy issue megoldva.

2024-02-24 20:39 UTC, kimaah requested changes
well ez igy nem jo, mert ugyan ezt a widget-et jeleniti meg a hianyoknal es a hianyzasoknal is tehat kell ket kulon forditas

2024-02-24 20:40 UTC, pml68 commented
Bruh

2024-02-24 20:40 UTC, pml68 commented
Gimme a sec

2024-02-24 21:58 UTC, pml68 commented
Done

2024-02-24 22:01 UTC, pml68 commented
Oh shit I'm stupid af

2024-02-25 20:35 UTC, merged

2024-02-25 20:35 UTC, pml68 commented
Thanks